export const locations:string[] = [
  "Dowleswaram",
  "kovvur",
  "kapavaram",
  "nidadavole",
  "tadipudi",
  "chagallu",
  "vemagiri",
  "korukonda",
  "gokavaram",
  "seethanagaram",
  "rangampeta",
  "biccavolu",
  "samalkota",
  "peddapuram",
  "kirlampudi",
  "jaggampeta",
  "gandepalli",
  "prathipadu",
  "yeleswaram",
  "addateegala",
  "rajavommangi",
  "tuni rural",
  "payakaraopeta",
  "nakkapalli",
  "kotauratla",
  "narsipatnam rural",
  "golugonda",
  "ravikamatham",
  "rolugunta",
  "makavarapalem",
  "kasimkota",
  "munagapaka",
  "anakapalle rural",
  "achutapuram",
  "paravada",
  "sabbavaram",
  "pendurthi rural",
  "anandapuram",
  "bheemunipatnam rural",
  "padmanabham",
  "chodavaram",
  "devarapalli",
  "cheedikada",
  "madugula",
  "kothakota",
  "paderu",
  "hukumpeta",
  "gajuwaka rural",
  "kurmannapalem",
  "madhurawada",
  "MVP Colony",
  "Madhurawada",
  "Rushikonda",
  "Yendada",
  "PM-Palem",
  "Seethammadhara",
  "Dwaraka Nagar",
  "Asilmetta",
  "Siripuram",
  "Waltair Uplands",
  "Lawsons Bay Colony",
  "Beach Road",
  "Jagadamba Junction",
  "Maharani-Peta",
  "Ramakrishna Beach",
  "Gajuwaka",
  "Akkayyapalem",
  "NAD Junction",
  "Gopalapatnam",
  "Simhachalam",
  "Pendurthi",
  "Bheemili",
  "Tagarapuvalasa",
  "Arilova",
  "HB-Colony",
  "Muralinagar",
  "Kommadi",
  "Vepagunta",
  "Kancharapalem",
  "Railway New Colony",
  "Allipuram",
  "Poorna Market",
  "One Town",
  "Old Post Office",
  "Pedagantyada",
  "Duvvada",
  "Steel Plant",
  "Scindia",
  "Town Kotha Road",
  "Whitefield",
  "Marathahalli",
  "Brookefield",
  "Bellandur",
  "Sarjapur Road",
  "Sarjapur",
  "HSR Layout",
  "BTM Layout",
  "Electronic City",
  "Electronic City Phase 2",
  "Koramangala",
  "Indira Nagar",
  "Domlur",
  "CV Raman Nagar",
  "Kaggadasapura",
  "Mahadevapura",
  "KR Puram",
  "Ramamurthy Nagar",
  "Banaswadi",
  "Horamavu",
  "Hennur",
  "Hennur Road",
  "Kalyan Nagar",
  "Kammanahalli",
  "Nagavara",
  "Thanisandra",
  "Hebbal",
  "Sahakara Nagar",
  "Yelahanka",
  "Jakkur",
  "Vidyaranyapura",
  "Yemalur",
  "Varthur",
  "Panathur",
  "Kadubeesanahalli",
  "Kadugodi",
  "ITPL Road",
  "Outer Ring Road",
  "Old Airport Road",
  "Old Madras Road",
  "Doddanekundi",
  "Munnekollal",
  "Kundalahalli",
  "AECS Layout",
  "Gunjur",
  "Gunjur Mugalur Road",
  "Harlur",
  "Kasavanahalli",
  "Chikkakannalli",
  "Doddakannalli",
  "Haralur Road",
  "Begur",
  "Bommanahalli",
  "Hongasandra",
  "Singasandra",
  "Hulimavu",
  "Bannerghatta Road",
  "JP Nagar",
  "Jayanagar",
  "Banashankari",
  "Uttarahalli",
  "Padmanabha Nagar",
  "Subramanyapura",
  "RR Nagar",
  "Kengeri",
  "Nagarbhavi",
  "Vijayanagar",
  "Rajaji Nagar",
  "Malleshwaram",
  "Yeshwanthpur",
  "Peenya",
  "Dasarahalli",
  "Mathikere",
  "RT Nagar",
  "Sadashiva Nagar",
  "Vasanth Nagar",
  "Frazer Town",
  "Cooke Town",
  "Cox Town",
  "Ulsoor",
  "MG Road",
  "Richmond Town",
  "Residency Road",
  "Shivaji Nagar",
  "Commercial Street",
  "Lavelle Road",
  "Langford Town",
  "Wilson Garden",
  "Shanthi Nagar",
  "Ejipura",
  "Neelasandra",
  "Benson Town",
  "HBR Layout",
  "Kothanur",
  "Byrathi",
  "Horamavu Agara",
  "Ramamurthy Nagar Extension"
];