export type ServiceFaq = {
  question: string;
  answer: string;
};

export type ServiceDetails = {
  slug: string;
  title: string;
  cardDescription: string;
  introduction: string;
  recommendation: string;
  materials: string;
  idealFor: string[];
  benefits: string[];
  images: string[];
  faqs: ServiceFaq[];
};

export const serviceCatalog: ServiceDetails[] = [
  {
    slug: "invisible-grills",
    title: "Invisible Grills",
    cardDescription: "Slim stainless-steel cables for safer balconies and windows without a heavy grille look.",
    introduction: "Invisible grills create a discreet safety barrier across open balconies and windows. Each installation is measured for the opening, tensioned carefully, and finished with neat anchor lines so the outside view stays open.",
    recommendation: "A strong choice when fall protection matters but you do not want conventional iron bars to dominate the elevation.",
    materials: "High-tensile stainless-steel cables with protective coating and corrosion-resistant fittings.",
    idealFor: ["High-rise balconies", "Apartment windows", "Children and pet safety"],
    benefits: ["Minimal visual obstruction", "Custom cable spacing", "Low-maintenance finish", "Made to fit each opening"],
    images: ["/invisble-grills-installation.webp", "/invisible-grills-for-balcony.webp", "/top-rated-invisible-grills.webp"],
    faqs: [
      { question: "Will invisible grills block the balcony view?", answer: "The slim vertical cables are designed to keep the view much more open than conventional bars while still forming a physical safety barrier." },
      { question: "Can the spacing be adjusted?", answer: "Yes. Cable spacing and anchor layout are planned after measuring the opening and understanding who the protection is for." },
    ],
  },
  {
    slug: "balcony-safety-nets",
    title: "Balcony Safety Nets",
    cardDescription: "Made-to-measure balcony netting that reduces fall risk while keeping light and ventilation.",
    introduction: "Balcony safety nets close dangerous gaps around railings, parapets, and open edges. We plan the fixing points around the actual balcony instead of forcing a standard-size net into the space.",
    recommendation: "Recommended for homes with young children, active pets, or open balcony edges that need an added layer of protection.",
    materials: "Weather-resistant netting selected for outdoor exposure, secured with suitable perimeter rope and anchors.",
    idealFor: ["Apartment balconies", "Open terraces", "Stair and utility openings"],
    benefits: ["Lightweight protection", "Keeps airflow", "Neat perimeter finish", "Replaceable when worn"],
    images: ["/balcony-1.webp", "/balcony-5.webp", "/balcony-safety-nets.webp"],
    faqs: [
      { question: "Is a balcony net suitable for a high-rise home?", answer: "It can be, provided the substrate, fixing points, net type, and installation method are suitable. We inspect the opening before recommending the setup." },
      { question: "Does the net need maintenance?", answer: "Check the net and its edge fixings periodically, especially after severe weather, renovation work, or any visible damage." },
    ],
  },
  {
    slug: "pigeon-safety-nets",
    title: "Pigeon Safety Nets",
    cardDescription: "Balcony and utility-area netting that stops pigeon entry without enclosing the space with metal cages.",
    introduction: "Pigeon nets close common entry routes around balconies, service shafts, and window recesses. A correctly measured installation helps prevent nesting and the repeated mess that follows.",
    recommendation: "Best for properties where birds regularly enter, roost, or build nests in a defined opening.",
    materials: "Outdoor-grade bird netting with perimeter rope and anchors chosen for the mounting surface.",
    idealFor: ["Balconies", "Utility areas", "Window recesses"],
    benefits: ["Stops bird entry", "Does not harm birds", "Easy-to-clean surroundings", "Low visual impact"],
    images: ["/transparabt-net-installation.webp", "/transparent-net-installation-near-me.webp", "/balcony-9.webp"],
    faqs: [
      { question: "Will birds get trapped in the net?", answer: "The purpose is to seal the opening so birds cannot enter. The edges must be fixed without gaps and the finished installation should be checked regularly." },
      { question: "Can the net be removed later?", answer: "Yes. The net can be replaced or removed while the suitability of reusing anchors depends on their condition." },
    ],
  },
  {
    slug: "anti-bird-nets",
    title: "Anti-Bird Nets",
    cardDescription: "Humane exclusion netting for larger bird-prone openings, ledges, courtyards, and building voids.",
    introduction: "Anti-bird nets are used where a larger opening or irregular structure needs to be protected from bird access. The layout is planned around ledges, pipes, corners, and maintenance access.",
    recommendation: "Suitable when pigeons or other birds enter a broad open area rather than one small balcony opening.",
    materials: "UV-stabilised bird-control netting with compatible support rope, hooks, and anchors.",
    idealFor: ["Building voids", "Commercial openings", "Courtyards and ledges"],
    benefits: ["Humane bird deterrence", "Covers irregular openings", "Reduces nesting areas", "Custom access options"],
    images: ["/anti-bird-nets-installation.webp", "/building-covering-safety-net.webp", "/balcony-6.webp"],
    faqs: [
      { question: "Are anti-bird nets harmful to birds?", answer: "A correctly installed exclusion net is intended to block access, not capture birds. The perimeter must be closed and inspected for damage." },
      { question: "Can you work around pipes or outdoor units?", answer: "Yes. Those details are considered during measurement so gaps are closed without preventing essential maintenance." },
    ],
  },
  {
    slug: "bird-spikes",
    title: "Bird Spikes",
    cardDescription: "Low-profile spike strips that discourage pigeons from landing on narrow ledges and parapets.",
    introduction: "Bird spikes make narrow landing surfaces uncomfortable for pigeons without relying on traps or poison. They work best on ledges, signboards, pipes, and parapets where birds perch but do not fly through an opening.",
    recommendation: "Use spikes for a landing surface; use bird netting when an entire opening needs to be sealed.",
    materials: "UV-resistant polycarbonate or stainless-steel spike systems, selected for the surface and exposure.",
    idealFor: ["Window ledges", "Parapet walls", "Signboards and pipes"],
    benefits: ["Humane deterrent", "Slim appearance", "Targeted installation", "Minimal upkeep"],
    images: ["/bird-spike-1.webp", "/bird-spike-2.webp", "/bird-spike-5.webp"],
    faqs: [
      { question: "Do bird spikes injure pigeons?", answer: "They are intended to remove a comfortable landing surface, not to trap birds. Correct spacing and secure installation are important." },
      { question: "Are spikes better than nets?", answer: "They solve different problems. Spikes suit ledges and parapets; nets suit balconies, shafts, and other open areas birds can enter." },
    ],
  },
  {
    slug: "duct-area-safety-nets",
    title: "Duct Area Safety Nets",
    cardDescription: "Purpose-fitted netting for open shafts and utility voids in apartment and commercial buildings.",
    introduction: "Duct and shaft openings can collect debris, allow bird entry, and create an avoidable fall hazard. We fit a net around the usable opening while considering pipes and maintenance access.",
    recommendation: "Recommended for open service shafts, duct voids, and utility areas that cannot be permanently closed.",
    materials: "Durable netting with perimeter supports suited to concrete, masonry, or metal fixing points.",
    idealFor: ["Apartment shafts", "Utility ducts", "Service openings"],
    benefits: ["Closes unsafe voids", "Helps stop bird entry", "Fits around services", "Access can be planned"],
    images: ["/duct-area.webp", "/cards/duct-area-safety-nets-near-me.webp", "/vent-cover-1.webp"],
    faqs: [
      { question: "Can technicians still access the duct?", answer: "An access section can be planned when regular maintenance is required. Tell us where access is needed during the site visit." },
      { question: "Can the net fit around existing pipes?", answer: "Yes. The opening is measured around fixed services so the perimeter can be closed neatly." },
    ],
  },
  {
    slug: "windows-safety-nets",
    title: "Window Safety Nets",
    cardDescription: "Custom window netting for added child, pet, and bird protection without heavy bars.",
    introduction: "Window safety nets create a lightweight barrier across openings that may otherwise be accessible to children, pets, or birds. The net is measured to the frame or surrounding wall for a clean edge.",
    recommendation: "Useful for apartment windows, ventilation openings, and utility windows where a full grille is not preferred.",
    materials: "Weather-resistant netting, edge rope, and surface-appropriate fixings.",
    idealFor: ["Apartment windows", "Utility windows", "Ventilation openings"],
    benefits: ["Custom fit", "Allows airflow", "Lightweight finish", "Multiple safety uses"],
    images: ["/window-safety-nets-installation.webp", "/anti-bird-nets-installation.webp", "/vent-cover-1.webp"],
    faqs: [
      { question: "Can a safety net replace every type of window grille?", answer: "Not always. The right system depends on the opening and the risk involved; we will recommend netting or an invisible grill after inspection." },
      { question: "Will the window still open?", answer: "That depends on the window style and fixing layout. We plan the installation around normal use wherever possible." },
    ],
  },
  {
    slug: "children-safety-nets",
    title: "Children Safety Nets",
    cardDescription: "An added protective barrier for balconies, windows, stairs, and other child-accessible openings.",
    introduction: "Children safety nets help close reachable gaps around balcony railings, windows, and stair openings. The installation is planned around the height, edge condition, and way the space is used.",
    recommendation: "Use as one layer of home safety alongside adult supervision, secure doors, and age-appropriate precautions.",
    materials: "Outdoor-grade netting with secure perimeter fixings selected for the opening.",
    idealFor: ["Balconies", "Windows", "Stair openings"],
    benefits: ["Closes reachable gaps", "Made to measure", "Keeps light and air", "Suitable for many openings"],
    images: ["/cards/balcony-safety-nets-near-me.webp", "/balcony-safety-nets.webp", "/balcony-5.webp"],
    faqs: [
      { question: "Is a net a substitute for supervision?", answer: "No. It is an added barrier, not a substitute for adult supervision or other child-safety measures." },
      { question: "How do you choose the fixing points?", answer: "We inspect the opening, surrounding surface, and likely loads before planning the perimeter anchors." },
    ],
  },
  {
    slug: "cat-safety-nets",
    title: "Cat Safety Nets",
    cardDescription: "Pet-focused netting that helps cats enjoy balconies and windows with less escape and fall risk.",
    introduction: "Cat safety nets close balcony and window gaps that curious pets may climb through. Attention is given to corners, railing gaps, overhead routes, and any nearby surface a cat can use as a step.",
    recommendation: "Recommended for indoor cats with access to balconies, windows, or utility areas.",
    materials: "Durable pet-suitable netting with a carefully closed perimeter and secure anchors.",
    idealFor: ["Cat balconies", "Open windows", "Pet-friendly apartments"],
    benefits: ["Helps prevent escapes", "Covers climbing routes", "Keeps the view open", "Custom perimeter fitting"],
    images: ["/balcony-9.webp", "/transparent-net-installation-near-me.webp", "/balcony-7.webp"],
    faqs: [
      { question: "Is ordinary pigeon netting always suitable for cats?", answer: "Not necessarily. The mesh, perimeter, and fixing plan should consider climbing, chewing, and the pet's size and behaviour." },
      { question: "Can you close the space above the railing?", answer: "Yes. We inspect possible escape routes and plan coverage for the full accessible opening." },
    ],
  },
  {
    slug: "monkey-safety-nets",
    title: "Monkey Safety Nets",
    cardDescription: "Stronger perimeter netting designed to reduce monkey entry into balconies and open residential areas.",
    introduction: "Monkey protection needs stronger material and fixing than a basic bird-control setup. We assess the access route, opening size, and surrounding structure before recommending coverage.",
    recommendation: "For homes and buildings in areas where monkeys regularly enter balconies, terraces, or utility spaces.",
    materials: "Heavy-duty netting and reinforced perimeter fixings chosen after site inspection.",
    idealFor: ["Balconies", "Terraces", "Open utility areas"],
    benefits: ["Stronger entry barrier", "Custom coverage", "Reinforced edges", "Non-electric solution"],
    images: ["/monkey-safety-nets.webp", "/building-covering-safety-net.webp", "/hdpe-3.webp"],
    faqs: [
      { question: "Is a standard bird net strong enough for monkeys?", answer: "Usually not. Monkey-prone areas require a heavier material and stronger anchors, selected after inspection." },
      { question: "Can you protect an entire terrace?", answer: "Coverage depends on the available structure and safe anchor points. We inspect the terrace before proposing a layout." },
    ],
  },
  {
    slug: "sports-nets",
    title: "Sports Nets",
    cardDescription: "Ball-stop and practice nets for cricket, terraces, schools, courts, and residential communities.",
    introduction: "Sports nets contain balls within practice and play areas, helping protect people, windows, vehicles, and neighbouring property. Height, mesh size, and support layout are selected for the activity.",
    recommendation: "Suitable for cricket practice, terrace play zones, schools, apartments, and compact sports facilities.",
    materials: "Activity-appropriate netting with supporting rope, poles, or structural anchors as the site requires.",
    idealFor: ["Cricket practice", "Apartment play areas", "Schools and courts"],
    benefits: ["Contains stray balls", "Custom height and span", "Indoor or outdoor options", "Replaceable net panels"],
    images: ["/sports-nets-installation.webp", "/sports-nets-installation-near-me.webp", "/event-1.webp"],
    faqs: [
      { question: "What mesh size do I need?", answer: "It depends on the sport and ball size. We recommend mesh and cord strength after confirming the activity and span." },
      { question: "Can sports nets be installed on a terrace?", answer: "Often yes, if suitable supports and safe anchor points are available. A site check is needed before confirming the design." },
    ],
  },
  {
    slug: "industrial-safety-nets",
    title: "Full-Building Safety Nets",
    cardDescription: "Large-format HDPE netting for building fronts, construction edges, and broad exterior openings.",
    introduction: "Full-building safety nets cover large façades and open elevations where smaller residential net systems are not appropriate. Each project needs a site-specific support and access plan.",
    recommendation: "For building exteriors, construction zones, warehouse openings, and other large spans that need controlled coverage.",
    materials: "Heavy-duty HDPE netting with reinforced edge rope and a support system designed for the span.",
    idealFor: ["Building façades", "Construction edges", "Warehouses and large openings"],
    benefits: ["Large-span coverage", "Reinforced perimeter", "Site-specific layout", "Outdoor-grade material"],
    images: ["/building-covering-safety-net.webp", "/hdpe-3.webp", "/hdpe-5.webp"],
    faqs: [
      { question: "Can the same net be used for every building?", answer: "No. Net grade, supports, access, exposure, and span must be reviewed for each site." },
      { question: "Do you inspect the building first?", answer: "Yes. Large-format work requires measurement and a review of safe fixing points before a quotation can be prepared." },
    ],
  },
  {
    slug: "cloth-hangers",
    title: "Ceiling Cloth Hangers",
    cardDescription: "Space-saving ceiling-mounted drying rods that lower for loading and lift clothes out of the way.",
    introduction: "Ceiling cloth hangers turn unused overhead space into an organised drying area. Individual rods can be lowered when needed and raised after loading, keeping the balcony or utility floor clear.",
    recommendation: "A practical fit for compact balconies, utility rooms, apartments, and homes with limited floor space.",
    materials: "Ceiling-mounted metal drying rods, rope-and-pulley controls, and fixings selected for the ceiling surface.",
    idealFor: ["Apartment balconies", "Utility rooms", "Compact laundry areas"],
    benefits: ["Saves floor space", "Rods move independently", "Comfortable loading height", "Neat ceiling storage"],
    images: ["/cloth-hanger-2.webp", "/cloth-hanger-3.webp", "/cloth-hanger-2.webp"],
    faqs: [
      { question: "How many rods can be installed?", answer: "The number and length of rods depend on the ceiling width, available drying space, and fixing surface." },
      { question: "Can each rod be lowered separately?", answer: "Yes. The pictured pulley-style system uses separate controls so you can lower only the rods you need." },
    ],
  },
  {
    slug: "terrace-safety-nets",
    title: "Terrace Safety Nets",
    cardDescription: "Perimeter and overhead netting for open terraces, rooftop play areas, and exposed residential edges.",
    introduction: "Terraces often combine long open edges, changing floor levels, water tanks, pipes, and limited fixing points. We measure the complete accessible area and plan coverage around those details instead of treating the terrace like an oversized balcony.",
    recommendation: "A useful option for residential rooftops and shared terraces where open edges or ball escape need to be controlled without constructing a permanent enclosure.",
    materials: "Outdoor-grade netting with reinforced edge rope and anchors selected for the parapet, wall, column, or available support structure.",
    idealFor: ["Residential rooftops", "Apartment terraces", "Terrace play areas"],
    benefits: ["Covers long open spans", "Plans around rooftop services", "Keeps the area ventilated", "Residential and play-area options"],
    images: ["/hdpe-5.webp", "/sports-nets-installation-near-me.webp", "/building-covering-safety-net.webp"],
    faqs: [
      { question: "Can a terrace be covered without drilling into the floor?", answer: "Possibly, but it depends on the parapet, columns, and other safe support points. We inspect the structure before deciding where the perimeter can be fixed." },
      { question: "Can one net provide both edge protection and ball control?", answer: "Sometimes. The mesh, height, cord strength, and support layout must suit both purposes; otherwise separate sections may be safer and easier to maintain." },
    ],
  },
  {
    slug: "staircase-safety-nets",
    title: "Staircase Safety Nets",
    cardDescription: "Custom net barriers for stair voids, railing gaps, landings, and open sides inside homes and buildings.",
    introduction: "Open stairwells can have tall drops, wide railing gaps, and irregular corners that standard rectangular nets do not cover neatly. We map the accessible openings and shape the perimeter around flights, landings, handrails, and walls.",
    recommendation: "Designed as an added barrier where children, pets, or dropped objects could reach an open stair void or pass through large railing gaps.",
    materials: "Interior- or outdoor-suitable netting with edge rope and fixings matched to concrete, masonry, metal, or suitable timber surfaces.",
    idealFor: ["Duplex homes", "Apartment stairwells", "Open landings and railings"],
    benefits: ["Fits irregular stair shapes", "Closes railing gaps", "Lightweight appearance", "Can follow multiple levels"],
    images: ["/cards/safety-nets.webp", "/balcony-7.webp", "/window-safety-nets-installation.webp"],
    faqs: [
      { question: "Can the net follow a sloping staircase?", answer: "Yes. The perimeter can be measured along the stair angle, provided suitable fixing points are available from the lower flight to the upper landing." },
      { question: "Does a staircase net replace a compliant railing?", answer: "No. It is an additional barrier and should not be treated as a substitute for structurally sound, code-compliant railings and adult supervision." },
    ],
  },
  {
    slug: "construction-safety-nets",
    title: "Construction Safety Nets",
    cardDescription: "Heavy-duty netting for active work zones, exposed building edges, scaffolding, and material-control areas.",
    introduction: "Construction sites change as each floor and work phase progresses. A useful netting plan must consider the present edge, the type of work, access for workers and materials, wind exposure, and how the system will be inspected or moved.",
    recommendation: "For contractors and property teams that need project-specific containment or edge netting planned around the current construction stage.",
    materials: "Heavy-duty HDPE or application-specific safety netting with reinforced borders, support rope, and an engineered fixing arrangement appropriate to the site.",
    idealFor: ["Building perimeters", "Scaffolding enclosures", "Material-control zones"],
    benefits: ["Planned for active work areas", "Large-span options", "Reinforced border treatment", "Phased installation support"],
    images: ["/building-covering-safety-net.webp", "/hdpe-3.webp", "/hdpe-5.webp"],
    faqs: [
      { question: "Is residential balcony netting suitable for construction work?", answer: "No. Construction applications require material, support, inspection, and installation decisions based on the specific site hazards and intended function." },
      { question: "Can the netting move as construction progresses?", answer: "A phased plan may be possible, but every relocation requires the supports, net condition, access, and new work area to be reviewed before reuse." },
    ],
  },
  {
    slug: "cricket-practice-nets",
    title: "Cricket Practice Nets",
    cardDescription: "Purpose-planned practice lanes that contain cricket balls and separate batting or bowling activity from nearby spaces.",
    introduction: "A cricket practice lane needs more than netting around four sides. Length, lane width, roof height, mesh size, impact zones, entry position, and clearance from walls or vehicles all influence how safely and comfortably the lane can be used.",
    recommendation: "For schools, academies, apartment communities, terraces, and private practice areas with a defined batting and bowling direction.",
    materials: "Cricket-suitable knotted or knotless netting with impact-appropriate cord, top and bottom supports, and poles or structural anchors where required.",
    idealFor: ["Cricket academies", "Schools and apartments", "Private practice lanes"],
    benefits: ["Contains practice balls", "Custom lane dimensions", "Indoor and outdoor layouts", "Separate entry can be planned"],
    images: ["/sports-nets-installation.webp", "/sports-nets-installation-near-me.webp", "/event-1.webp"],
    faqs: [
      { question: "How large should a cricket practice lane be?", answer: "The available site, player age, bowling run-up, roof clearance, and surrounding property determine the practical dimensions. We measure the area before proposing a layout." },
      { question: "Can a cricket net be installed on a rooftop?", answer: "It may be possible where safe supports and adequate height are available. Wind exposure, anchor points, and neighbouring areas need particular attention on terraces." },
    ],
  },
  {
    slug: "ventilation-area-nets",
    title: "Ventilation Area Nets",
    cardDescription: "Neat mesh coverage for vents, exhaust openings, utility cut-outs, and other small bird-entry points.",
    introduction: "Small ventilation openings are easy to overlook but can become regular entry points for pigeons and other birds. We close the usable perimeter while keeping the vent, exhaust path, or service opening accessible for its intended function.",
    recommendation: "Best for compact openings where full balcony netting would be unnecessary and bird spikes would not stop entry through the gap.",
    materials: "Fine, weather-resistant netting or mesh with a frame or perimeter fixing method suitable for the vent and surrounding wall.",
    idealFor: ["Exhaust openings", "Utility vents", "Small service cut-outs"],
    benefits: ["Targets small entry points", "Keeps ventilation paths open", "Fits around ducts and pipes", "Discreet installation"],
    images: ["/vent-cover-1.webp", "/duct-area.webp", "/window-safety-nets-installation.webp"],
    faqs: [
      { question: "Will the net reduce ventilation?", answer: "Any mesh creates some resistance, so the opening and airflow requirement must be considered. We avoid blocking powered exhausts or required ventilation clearances." },
      { question: "Can the cover be opened for servicing?", answer: "Where routine maintenance is needed, a removable or accessible section can be considered during measurement." },
    ],
  },
  {
    slug: "transparent-safety-nets",
    title: "Transparent Safety Nets",
    cardDescription: "Low-visibility netting for balconies and windows where an open, lighter-looking finish is a priority.",
    introduction: "Transparent safety nets use a less visually prominent line to reduce the enclosed appearance of a balcony or window. Because colour and thickness affect visibility, strength, and ageing, we explain the available material before recommending it for the opening.",
    recommendation: "For homeowners who prefer a subtle net finish and whose opening, exposure, and intended safety use are suitable for the selected material.",
    materials: "Clear or translucent outdoor-suitable netting with matching perimeter line and surface-appropriate anchors.",
    idealFor: ["View-facing balconies", "Apartment windows", "Light-coloured interiors"],
    benefits: ["Lower visual contrast", "Preserves light and airflow", "Measured perimeter fit", "Balcony and window options"],
    images: ["/transparent-net-installation-near-me.webp", "/transparabt-net-installation.webp", "/transnparent-9.webp"],
    faqs: [
      { question: "Is a transparent net completely invisible?", answer: "No. It is less visually prominent than many dark nets, but it remains visible at certain angles and in changing light." },
      { question: "Is transparent netting the strongest option?", answer: "Not automatically. Strength depends on the specific material, line thickness, mesh, fixing layout, and intended use. We compare those factors before recommending it." },
    ],
  },
  {
    slug: "safety-net-installation",
    title: "Custom Safety Net Installation",
    cardDescription: "Measured and fitted netting for unusual openings that do not match a standard service category.",
    introduction: "Some openings need a custom solution rather than a standard balcony or window net. We inspect the span, mounting surfaces, intended use, and access needs before choosing the net and fixing plan.",
    recommendation: "Choose this service for terraces, stair voids, event areas, or unusual residential and commercial openings.",
    materials: "Net type, cord strength, edge rope, and anchors selected for the intended use and site conditions.",
    idealFor: ["Unusual openings", "Terraces and stairs", "Temporary or special-use areas"],
    benefits: ["Site-specific planning", "Multiple net grades", "Custom edge treatment", "Residential and commercial use"],
    images: ["/safety-nets-installation.webp", "/event-1.webp", "/hdpe-5.webp"],
    faqs: [
      { question: "How do I know which net I need?", answer: "Share photos and dimensions for an initial discussion. We confirm the appropriate material and fixing method after checking the site." },
      { question: "Can you work with an irregular shape?", answer: "Usually yes. The opening is measured and the perimeter layout is planned around corners, services, and access requirements." },
    ],
  },
];

export const serviceBySlug = Object.fromEntries(
  serviceCatalog.map((service) => [service.slug, service]),
) as Record<string, ServiceDetails>;
